### ISSUE TITLE
install_rubies attribute

### ISSUE THREAD

**Issue by thomasdarde** [fnichol/chef-rvm#297]
I've been in real pain to use chef-rvm, the readme doesn't specify we need to set install_rubies to true to install rubies...

```
default['rvm']['install_rubies'] = "true"
```
 
Is it a problem in my config which make this attribute necessary ? Or should we add it to the readme (I'll propose a PR if it is)

Thanks !

**Comment by martinisoft** [comment]
Hi @thomasdarde 

This could be documented for now (send a PR) but it will eventually go away. The idea for now is to finish rewriting the LWRP and get the old functionality to utilize that. Afterward, it will either get extracted into a public wrapper cookbook or removed entirely.

**Comment by mshappe** [comment]
Actually, right at the moment, **nothing** I do, including the above, seems to actually get rubies installed.  Something has broken recently, because I know this was working.

**Comment by martinisoft** [comment]
@mshappe master definitely has issues because of the partial re-write and the previously released versions have some workarounds. A lot of these interfaces will basically go away beyond the re-write to make this cookbook more re-usable as a library cookbook. Sorry this has caused you a lot of trouble. We're working on it. :)

**Comment by thomasdarde** [comment]
I'm using version 7e1d452eeda083c1048ea94d513b58df78ad5350
Attributes : 
```
default['rvm']['default_ruby'] = "ruby-2.2.0"
default['rvm']['rubies'] = ["ruby-2.2.0"]
default['rvm']['install_rubies'] = "true"
```
Working fine .

**Comment by mshappe** [comment]
@thomasdarde That looks like it's intended for system-wide install. I use a user-level install, religiously :smile: It's definitely broken.

What does work is the `rvm::user_install` recipe, followed by an explicit:

```
rvm_ruby '2.1.2' do
  user <username>
end
```

**Comment by mshappe** [comment]
@martinisoft I understand, and that's all good...except that if you read the README, it rather confidently describe what's **supposed** to happen on master, rather than what actually does. I realize this is a philosophical argument that could go on all day, but IMO, the README on an open source project's "master" branch should describe what master currently does, **and** what's broken, so that people can actually, y'know, use the thing :smile:

**Comment by martinisoft** [comment]
@mshappe Fair point. Will update the README today.

**Comment by egzplicit** [comment]
This is still not in the README file.
